# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Parafia św. Katarzyny i św. Jana Apostoła w Seceminie
paginate:       5
baseurl:        "/blogFin"
url:            "https://justyna1adam.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Justyna Adamczyk
  email:        justyna1adamczyk@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/justyna1adam/blogFin

# Gems
gems:
  - jekyll-paginate
